# Generated by Django 6.0.3 on 2026-03-16 19:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('paused', 'Paused')], default='active', max_length=20)),
                ('camera_source', models.CharField(default='0', max_length=50)),
                ('total_students', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'class_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('seat_row', models.IntegerField(default=1)),
                ('seat_col', models.IntegerField(default=1)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='ClassEngagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('avg_engagement', models.FloatField(default=0.0)),
                ('avg_attention', models.FloatField(default=0.0)),
                ('present_count', models.IntegerField(default=0)),
                ('emotion_distribution', models.TextField(default='{}')),
                ('confusion_alert', models.BooleanField(default=False)),
                ('low_engagement_alert', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='engagement.classsession')),
            ],
            options={
                'db_table': 'class_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_engagement', 'Low Engagement'), ('confused', 'Confused'), ('distracted', 'Distracted'), ('absent', 'Absent'), ('class_confusion', 'Class Confusion'), ('bored', 'Bored')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='engagement.classsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='engagement.student')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='engagement.teacher'),
        ),
        migrations.CreateModel(
            name='EngagementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('attention_score', models.FloatField(default=0.0)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprise', 'Surprise'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('confused', 'Confused'), ('bored', 'Bored'), ('focused', 'Focused'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('emotion_confidence', models.FloatField(default=0.0)),
                ('emotion_scores', models.TextField(blank=True, default='{}')),
                ('head_angle', models.FloatField(default=0.0)),
                ('eye_contact', models.BooleanField(default=False)),
                ('posture_score', models.FloatField(default=0.0)),
                ('is_slouching', models.BooleanField(default=False)),
                ('face_detected', models.BooleanField(default=False)),
                ('face_confidence', models.FloatField(default=0.0)),
                ('face_bbox', models.CharField(blank=True, default='', max_length=100)),
                ('frame_path', models.CharField(blank=True, default='', max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_records', to='engagement.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_records', to='engagement.student')),
            ],
            options={
                'db_table': 'engagement_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'session'], name='engagement__student_506eb7_idx'), models.Index(fields=['timestamp'], name='engagement__timesta_bd11ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='engagement.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='engagement.student')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('student', 'session', 'date')},
            },
        ),
    ]
