# Generated by Django 5.2.12 on 2026-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('engagement', 'Engagement Report'), ('attendance', 'Attendance Report'), ('performance', 'Performance Report'), ('emotion', 'Emotion Analysis'), ('summary', 'Summary Report')], max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('xlsx', 'Excel')], default='csv', max_length=5)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('student_ids', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
