# Generated by Django 5.2.12 on 2026-03-19 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0.0)),
                ('comment', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'lecture_feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120)),
                ('unit', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('planned_date', models.DateField(default=django.utils.timezone.now)),
                ('revised_date', models.DateField(blank=True, null=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('checkpoint_assigned', models.BooleanField(default=False)),
                ('checkpoint_completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_topics', to='engagement.teacher')),
            ],
            options={
                'db_table': 'syllabus_topics',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraLecturePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_lectures', to='engagement.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_lectures', to='engagement.syllabustopic')),
            ],
            options={
                'db_table': 'extra_lecture_plans',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percent', models.FloatField(default=0.0)),
                ('needs_extra_lecture', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='engagement.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='engagement.syllabustopic')),
            ],
            options={
                'db_table': 'student_topic_progress',
                'unique_together': {('student', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='DailyLectureTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='engagement.syllabustopic')),
            ],
            options={
                'db_table': 'daily_lecture_topics',
                'ordering': ['-lecture_date', 'topic__topic'],
                'unique_together': {('topic', 'lecture_date')},
            },
        ),
    ]
