# Generated by Django 6.0.3 on 2026-03-21 10:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_lecturefeedback_syllabustopic_extralectureplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementrecord',
            name='engagement_trend',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='student',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('system', 'System'), ('info', 'Info')], default='alert', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='engagement.student')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('engagement_trend', models.TextField(default='{}')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('recommendation_text', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='engagement.student')),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-week_start_date'],
                'unique_together': {('student', 'week_start_date')},
            },
        ),
    ]
