# Generated by Django 6.0.3 on 2026-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_engagementrecord_engagement_trend_student_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/profiles/'),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='engagement_trend',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='engagementrecord',
            name='engagement_trend',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
